### ISSUE TITLE
DllInjector.ini

### ISSUE THREAD

**Issue by Bubiko** [ImaniiTy/GreenLuma-Reborn-Manager#50]
ERROR:root:Traceback (most recent call last):
  File "Qt\logic.py", line 208, in run_GLR
  File "Qt\logic.py", line 316, in replaceConfig
  File "fileinput.py", line 249, in __next__
  File "fileinput.py", line 343, in _readline
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Program Files (x86)\\Steam/DllInjector.ini' -> 'C:\\Program Files (x86)\\Steam/DllInjector.ini.bak'
NoneType: None

**Comment by Evolutiine** [comment]
same here. What's going on??

**Comment by Bubiko** [comment]
If you have the same problem and the app didn't run because of the dllinjector you can send me a message and I will send to you my dllinjector (bubi#7777 on discord)

**Comment by Evolutiine** [comment]
> 

sent you a FR on discord. Thank you!

**Comment by testingstuffagain** [comment]
same ??
but whats your discord?

**Comment by braydengorillatag** [comment]
> same ?? but whats your discord?

yeah when i do it it does not work
